server {
    listen 80;
    listen [::]:80;

    server_name syncly.lyricweb.ru;

    root /var/www/syncly.lyricweb.ru/current;
    index index.html;

    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_vary on;
    gzip_types application/javascript application/json image/svg+xml text/css text/javascript text/plain;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
    }

    location /assets/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }

    location /avatars/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=604800" always;
    }

    location = /index.html {
        add_header Cache-Control "no-cache" always;
    }

    location / {
        add_header Cache-Control "no-cache" always;
        try_files $uri $uri/ /index.html;
    }

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
