export const routes = {
  home: '/',
  join: (inviteToken: string) => `/join/${inviteToken}`,
  joinPattern: '/join/:inviteToken',
  legacySignUp: '/register',
  characterEditorSmokeTest: '/__character-editor-smoke',
  playerSmokeTest: '/__player-smoke',
  profileOnboardingSmokeTest: '/__profile-onboarding-smoke',
  roomsSmokeTest: '/__rooms-smoke',
  leaveRoomSmokeTest: '/__leave-room-smoke',
  room: (roomId: string) => `/rooms/${roomId}`,
  roomPattern: '/rooms/:roomId',
  rooms: '/rooms',
  signIn: '/sign-in',
  signUp: '/sign-up',
} as const
